"""modelos iniciales

Revision ID: 0177f417c611
Revises: 
Create Date: 2026-09-27 18:28:13.903298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0177f417c611'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orquestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('orquesta_directo', 'orquesta_playback', name='tipo_orquesta'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('num_musicos', sa.Integer(), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('verificada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orquestas_email'), 'orquestas', ['email'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('ayuntamiento', 'junta_vecinal', 'comision_fiestas', 'particular', name='tipo_usuario'), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=9), nullable=True),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('disponibilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orquesta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'reservado', 'no_disponible', name='estado_disponibilidad'), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['orquesta_id'], ['orquestas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orquesta_id', 'fecha', name='uix_orquesta_fecha')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('disponibilidad_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aceptada', 'rechazada', name='estado_reserva'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disponibilidad_id'], ['disponibilidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_reserva_aceptada_por_disponibilidad', 'reservas', ['disponibilidad_id'], unique=True, postgresql_where=sa.text("estado = 'aceptada'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reserva_aceptada_por_disponibilidad', table_name='reservas', postgresql_where=sa.text("estado = 'aceptada'"))
    op.drop_table('reservas')
    op.drop_table('disponibilidades')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_orquestas_email'), table_name='orquestas')
    op.drop_table('orquestas')
    sa.Enum(name="estado_reserva").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="estado_disponibilidad").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="tipo_usuario").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="tipo_orquesta").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
